In [1]:
import pandas as pd

df = pd.read_csv('data/match_results/PremierLeague.csv')

print(df.head())

      Season        Date Time     HomeTeam        AwayTeam  \
0  1993-1994  14/08/1993  NaN      Arsenal        Coventry   
1  1993-1994  14/08/1993  NaN  Aston Villa             QPR   
2  1993-1994  14/08/1993  NaN      Chelsea       Blackburn   
3  1993-1994  14/08/1993  NaN    Liverpool  Sheffield Weds   
4  1993-1994  14/08/1993  NaN     Man City           Leeds   

   FullTimeHomeTeamGoals  FullTimeAwayTeamGoals FullTimeResult  \
0                      0                      3              A   
1                      4                      1              H   
2                      1                      2              A   
3                      2                      0              H   
4                      1                      1              D   

   HalfTimeHomeTeamGoals  HalfTimeAwayTeamGoals  ... MarketMaxHomeTeam  \
0                    NaN                    NaN  ...               NaN   
1                    NaN                    NaN  ...               NaN   
2       

In [2]:
max_values = df['B365HomeTeam'].max()

In [3]:
print(max_values)

23.0


In [4]:
df = df.iloc[9881:].reset_index(drop=True)

In [5]:
print(df.head(20))

       Season        Date           Time          HomeTeam          AwayTeam  \
0   2019-2020  10/08/2019  12:30:00 p.m.          West Ham          Man City   
1   2019-2020  10/08/2019   3:00:00 p.m.       Bournemouth  Sheffield United   
2   2019-2020  10/08/2019   3:00:00 p.m.           Burnley       Southampton   
3   2019-2020  10/08/2019   3:00:00 p.m.    Crystal Palace           Everton   
4   2019-2020  10/08/2019   3:00:00 p.m.           Watford          Brighton   
5   2019-2020  10/08/2019   5:30:00 p.m.         Tottenham       Aston Villa   
6   2019-2020  11/08/2019   2:00:00 p.m.         Leicester            Wolves   
7   2019-2020  11/08/2019   2:00:00 p.m.         Newcastle           Arsenal   
8   2019-2020  11/08/2019   4:30:00 p.m.        Man United           Chelsea   
9   2019-2020  17/08/2019  12:30:00 p.m.           Arsenal           Burnley   
10  2019-2020  17/08/2019   3:00:00 p.m.       Aston Villa       Bournemouth   
11  2019-2020  17/08/2019   3:00:00 p.m.

In [6]:
print(df.shape)

(1899, 39)


In [7]:
print(df.describe())

       FullTimeHomeTeamGoals  FullTimeAwayTeamGoals  HalfTimeHomeTeamGoals  \
count            1899.000000            1899.000000            1899.000000   
mean                1.561875               1.310163               0.706161   
std                 1.343422               1.239139               0.856402   
min                 0.000000               0.000000               0.000000   
25%                 1.000000               0.000000               0.000000   
50%                 1.000000               1.000000               1.000000   
75%                 2.000000               2.000000               1.000000   
max                 9.000000               9.000000               5.000000   

       HalfTimeAwayTeamGoals  HomeTeamShots  AwayTeamShots  \
count            1899.000000    1899.000000    1899.000000   
mean                0.587151      13.867825      11.598210   
std                 0.789261       5.756465       5.189986   
min                 0.000000       1.000000      

In [8]:
# defining a home_team_win, home_team_draw, and home_team_lose columns which will be my y (output) training variable
# Define the function to classify match outcomes

def classify_outcome(row):
    if row['FullTimeResult'] == 'H':
        return pd.Series([1, 0, 0], index=['home_team_win', 'home_team_draw', 'home_team_lose'])
    elif row['FullTimeResult'] == 'D':
        return pd.Series([0, 1, 0], index=['home_team_win', 'home_team_draw', 'home_team_lose'])
    else:
        return pd.Series([0, 0, 1], index=['home_team_win', 'home_team_draw', 'home_team_lose'])

# Apply the function to each row in the DataFrame
df[['home_team_win', 'home_team_draw', 'home_team_lose']] = df.apply(classify_outcome, axis=1)

print("DataFrame with Outcome Classification:")
print(df)

DataFrame with Outcome Classification:
         Season        Date           Time          HomeTeam  \
0     2019-2020  10/08/2019  12:30:00 p.m.          West Ham   
1     2019-2020  10/08/2019   3:00:00 p.m.       Bournemouth   
2     2019-2020  10/08/2019   3:00:00 p.m.           Burnley   
3     2019-2020  10/08/2019   3:00:00 p.m.    Crystal Palace   
4     2019-2020  10/08/2019   3:00:00 p.m.           Watford   
...         ...         ...            ...               ...   
1894  2023-2024  19/05/2024   4:00:00 p.m.    Crystal Palace   
1895  2023-2024  19/05/2024   4:00:00 p.m.         Liverpool   
1896  2023-2024  19/05/2024   4:00:00 p.m.             Luton   
1897  2023-2024  19/05/2024   4:00:00 p.m.          Man City   
1898  2023-2024  19/05/2024   4:00:00 p.m.  Sheffield United   

              AwayTeam  FullTimeHomeTeamGoals  FullTimeAwayTeamGoals  \
0             Man City                      0                      5   
1     Sheffield United                      1   

In [9]:
# feature selection - drop the stats I don't know before the game

df = df.drop(columns=['Date','Time', 'Referee', 'FullTimeHomeTeamGoals','FullTimeAwayTeamGoals', 'FullTimeResult', 'HalfTimeHomeTeamGoals', 'HalfTimeAwayTeamGoals', 'HalfTimeResult', 'HomeTeamShots', 'AwayTeamShots', 'HomeTeamShotsOnTarget', 'AwayTeamShotsOnTarget', 'HomeTeamCorners', 'AwayTeamCorners', 'HomeTeamFouls', 'AwayTeamFouls', 'HomeTeamYellowCards', 'AwayTeamYellowCards', 'HomeTeamRedCards', 'AwayTeamReadCards'])

In [10]:
print(df.columns)

Index(['Season', 'HomeTeam', 'AwayTeam', 'B365HomeTeam', 'B365Draw',
       'B365AwayTeam', 'B365Over2.5Goals', 'B365Under2.5Goals',
       'MarketMaxHomeTeam', 'MarketMaxDraw', 'MarketMaxAwayTeam',
       'MarketAvgHomeTeam', 'MarketAvgDraw', 'MarketAvgAwayTeam',
       'MarketMaxOver2.5Goals', 'MarketMaxUnder2.5Goals',
       'MarketAvgOver2.5Goals', 'MarketAvgUnder2.5Goals', 'home_team_win',
       'home_team_draw', 'home_team_lose'],
      dtype='object')


In [11]:
# #one-hot encode categorical variables
# from sklearn.preprocessing import OneHotEncoder

# # Initialize OneHotEncoder
# encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')

# # Encode the Season column
# season_encoded = encoder.fit_transform(df[['Season']])
# season_encoded_df = pd.DataFrame(season_encoded, columns=encoder.get_feature_names_out(['Season']))

# # # Encode the HomeTeam column
# # home_team_encoded = encoder.fit_transform(df[['HomeTeam']])
# # home_team_encoded_df = pd.DataFrame(home_team_encoded, columns=encoder.get_feature_names_out(['HomeTeam']))

# # # Encode the AwayTeam column
# # away_team_encoded = encoder.fit_transform(df[['AwayTeam']])
# # away_team_encoded_df = pd.DataFrame(away_team_encoded, columns=encoder.get_feature_names_out(['AwayTeam']))

# # # Concatenate the original DataFrame with the new one-hot encoded columns
# # df = pd.concat([df.drop(columns=['Season', 'HomeTeam', 'AwayTeam']),
# #                         season_encoded_df, home_team_encoded_df, away_team_encoded_df], axis=1)

# df = pd.concat([df.drop(columns=['Season']), season_encoded_df], axis=1)

# print("DataFrame with One-Hot Encoded Columns:")
# print(df.head(10))

In [12]:
print(df['HomeTeam'].unique())

['West Ham' 'Bournemouth' 'Burnley' 'Crystal Palace' 'Watford' 'Tottenham'
 'Leicester' 'Newcastle' 'Man United' 'Arsenal' 'Aston Villa' 'Brighton'
 'Everton' 'Norwich' 'Southampton' 'Man City' 'Sheffield United' 'Chelsea'
 'Wolves' 'Liverpool' 'Fulham' 'West Brom' 'Leeds' 'Brentford'
 "Nott'm Forest" 'Luton']


In [13]:
# FEATURE ENGINEERING!
#I need to decrease the amount of features passed into the neural network, might help with overfitting issue
#Also instead of including every single team, make two new data columns called "home team rating" and "away team rating"
#this would output the relative strength of each team today!
# got the elos from http://clubelo.com/ENG
# remember to min-max scale the ranking afterwards

team_elo_ratings = {
    'Man City': 2051,
    'Arsenal': 1947,
    'Liverpool': 1901,
    'Chelsea': 1810,
    'Newcastle': 1802,
    'Tottenham': 1791,
    'Man United': 1779,
    'Aston Villa': 1770,
    'Crystal Palace': 1760,
    'West Ham': 1726,
    'Fulham': 1716,
    'Brighton': 1713,
    'Brentford': 1711,
    'Everton': 1707,
    'Bournemouth': 1691,
    'Wolves': 1678,
    'Burnley': 1611,
    'Luton': 1564,
    'Sheffield United': 1517,
    'Leicester': 1644,
    'Leeds': 1607,
    'Southampton': 1600,
    'Watford': 1466,
    'West Brom': 1524,
    'Nott\'m Forest': 1648,
    'Norwich': 1514,
}

# Map ELO ratings to the DataFrame
df['home_team_ELO'] = df['HomeTeam'].map(team_elo_ratings)
df['away_team_ELO'] = df['AwayTeam'].map(team_elo_ratings)

# Save the dropped columns
dropped_columns = df[['HomeTeam', 'AwayTeam']]

# Drop the columns
df = df.drop(columns=['HomeTeam', 'AwayTeam'])

print("DataFrame after dropping columns:")
print(df)


DataFrame after dropping columns:
         Season  B365HomeTeam  B365Draw  B365AwayTeam  B365Over2.5Goals  \
0     2019-2020         12.00      6.50          1.22              1.44   
1     2019-2020          1.95      3.60          3.60              1.90   
2     2019-2020          2.62      3.20          2.75              2.10   
3     2019-2020          3.00      3.25          2.37              2.20   
4     2019-2020          1.90      3.40          4.00              2.10   
...         ...           ...       ...           ...               ...   
1894  2023-2024          1.85      4.33          3.60              1.40   
1895  2023-2024          1.17      8.00         15.00              1.22   
1896  2023-2024          2.90      3.90          2.20              1.44   
1897  2023-2024          1.08     12.00         21.00              1.20   
1898  2023-2024          7.00      6.00          1.33              1.22   

      B365Under2.5Goals  MarketMaxHomeTeam  MarketMaxDraw  Market

In [14]:
df = df.drop(columns=['B365Over2.5Goals','B365Under2.5Goals', 'MarketMaxOver2.5Goals', 'MarketMaxUnder2.5Goals', 'MarketAvgOver2.5Goals', 'MarketAvgUnder2.5Goals', 'Season'])

print(df.columns)
print(df.shape)

#dataset of ~2000 games

Index(['B365HomeTeam', 'B365Draw', 'B365AwayTeam', 'MarketMaxHomeTeam',
       'MarketMaxDraw', 'MarketMaxAwayTeam', 'MarketAvgHomeTeam',
       'MarketAvgDraw', 'MarketAvgAwayTeam', 'home_team_win', 'home_team_draw',
       'home_team_lose', 'home_team_ELO', 'away_team_ELO'],
      dtype='object')
(1899, 14)


In [15]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [16]:
from sklearn.model_selection import train_test_split
import tensorflow as tf

# Split into training and testing data
X_train, temp = train_test_split(df, test_size=0.2, random_state=42)
X_val, X_test = train_test_split(temp, test_size=0.5, random_state=42)


# Separate features (X) and target variables (Y)
y_train = X_train[['home_team_win', 'home_team_draw', 'home_team_lose']]
X_train = X_train.drop(columns=['home_team_win', 'home_team_draw', 'home_team_lose'])

y_val = X_val[['home_team_win', 'home_team_draw', 'home_team_lose']]
X_val = X_val.drop(columns=['home_team_win', 'home_team_draw', 'home_team_lose'])

y_test = X_test[['home_team_win', 'home_team_draw', 'home_team_lose']]
X_test = X_test.drop(columns=['home_team_win', 'home_team_draw', 'home_team_lose'])

In [17]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.fit_transform(X_val)
X_test = scaler.fit_transform(X_test)

In [18]:
print("Training set:")
print(X_train.shape)
print(y_train.shape)
print(X_train)
print(y_train)

Training set:
(1519, 11)
(1519, 3)
[[0.00627353 0.5        0.49748744 ... 0.42586491 0.74358974 0.24102564]
 [0.04642409 0.1        0.10265614 ... 0.08511807 0.42222222 0.31111111]
 [0.01882058 0.225      0.24623116 ... 0.17517847 0.82222222 0.57435897]
 ...
 [0.2314931  0.1        0.0201005  ... 0.01565074 0.53504274 1.        ]
 [0.03074028 0.15       0.14752333 ... 0.12493136 1.         0.82222222]
 [0.05269762 0.04       0.11450108 ... 0.0826469  0.41196581 0.5025641 ]]
      home_team_win  home_team_draw  home_team_lose
1005              1               0               0
1793              1               0               0
1774              1               0               0
339               0               0               1
824               0               1               0
...             ...             ...             ...
1130              0               0               1
1294              0               0               1
860               0               0               1
1

In [19]:
from sklearn.preprocessing import LabelEncoder

# Assuming y_train is your one-hot encoded DataFrame
# Convert one-hot encoded columns to a single categorical column
y_train_single = y_train.idxmax(axis=1)

print("Single Column Categorical Target:")
print(y_train_single)

# Encode the categorical target variable
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train_single)

print("Encoded Target Values:")
print(y_train)

# Repeat the same process for y_cv and y_test
y_val_single = y_val.idxmax(axis=1)
y_val = label_encoder.transform(y_val_single)

y_test_single = y_test.idxmax(axis=1)
y_test = label_encoder.transform(y_test_single)

print("Encoded Cross-Validation Target Values:")
print(y_val)

print("Encoded Test Target Values:")
print(y_test)

Single Column Categorical Target:
1005     home_team_win
1793     home_team_win
1774     home_team_win
339     home_team_lose
824     home_team_draw
             ...      
1130    home_team_lose
1294    home_team_lose
860     home_team_lose
1459     home_team_win
1126     home_team_win
Length: 1519, dtype: object
Encoded Target Values:
[2 2 2 ... 1 2 2]
Encoded Cross-Validation Target Values:
[0 2 1 1 1 2 0 2 1 0 0 2 1 2 2 1 2 1 1 0 0 1 0 2 1 2 0 0 1 1 0 1 1 1 1 1 2
 0 1 2 2 1 2 0 2 1 2 1 2 2 2 2 0 2 1 2 1 1 1 1 1 1 2 0 2 2 2 2 2 0 2 1 1 0
 1 1 2 2 1 1 2 2 1 1 2 0 2 2 2 2 2 2 2 2 0 1 1 0 1 0 2 1 2 2 2 1 2 2 0 2 1
 0 1 2 2 2 2 1 1 0 2 2 0 1 2 1 2 0 2 1 2 2 1 0 0 1 1 1 1 1 2 2 0 1 2 1 2 1
 2 2 1 1 1 2 0 1 2 2 2 0 2 0 2 2 0 2 1 2 1 1 0 0 1 0 2 0 2 2 0 1 1 1 2 2 1
 0 0 2 2 0]
Encoded Test Target Values:
[1 1 0 2 2 2 2 0 2 2 2 1 0 1 0 1 1 2 0 2 2 2 0 2 0 2 2 1 1 2 1 2 1 0 0 1 0
 0 2 0 2 1 0 1 0 1 2 2 2 2 0 2 0 2 2 2 0 1 2 1 2 0 1 2 2 1 0 0 1 0 1 2 1 2
 0 2 1 1 0 0 0 2 2 2 0 2 2 1 2 2 1 2 2 

In [20]:
print(X_train)

[[0.00627353 0.5        0.49748744 ... 0.42586491 0.74358974 0.24102564]
 [0.04642409 0.1        0.10265614 ... 0.08511807 0.42222222 0.31111111]
 [0.01882058 0.225      0.24623116 ... 0.17517847 0.82222222 0.57435897]
 ...
 [0.2314931  0.1        0.0201005  ... 0.01565074 0.53504274 1.        ]
 [0.03074028 0.15       0.14752333 ... 0.12493136 1.         0.82222222]
 [0.05269762 0.04       0.11450108 ... 0.0826469  0.41196581 0.5025641 ]]


In [21]:
## NEURAL NETWORK ARCHITECTURE TESTING

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense, Input
from keras.models import Sequential
from tensorflow.keras.losses import SparseCategoricalCrossentropy

model = Sequential([
    Input(shape=X_train.shape[1:11]),
    Dense(30, activation="relu"),
    Dense(3, activation="softmax"),
])

# use categorical cross-entropy loss function bc we have one target probability per class for each distance
model.compile(optimizer='adam', loss=SparseCategoricalCrossentropy, metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=1000, validation_data=(X_val, y_val))

In [ ]:
import matplotlib.pyplot as plt

pd.DataFrame(history.history).plot(figsize=(8,5))
plt.grid(True)
plt.gca().set_ylim(0,1)
plt.show()

In [ ]:
# using more numerically accurate implementation of softmax, changing Adam to SGD and explicitly entering in learning rate

import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense, Input
from keras.models import Sequential
from keras.losses import CategoricalCrossentropy
from keras.optimizers import SGD

model = Sequential([
    Input(shape=(11,)),
    Dense(300, activation="relu"),
    Dense(100, activation="relu"),
    Dense(3, activation="linear"),
])

model.compile(optimizer=SGD(learning_rate=0.01, momentum=0.9), loss=CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_val, y_val))

In [ ]:
import matplotlib.pyplot as plt

pd.DataFrame(history.history).plot(figsize=(8,5))
plt.grid(True)
plt.gca().set_ylim(0,1)
plt.show()

In [ ]:
# using more numerically accurate implementation of softmax, changing Adam to SGD and explicitly entering in learning rate

import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense, Input
from keras.models import Sequential
from keras.losses import CategoricalCrossentropy

model = Sequential([
    Input(shape=X_train.shape[1:]),
    Dense(300, activation="relu"),
    Dense(100, activation="relu"),
    Dense(3, activation="linear"),
])

model.compile(optimizer="adam", loss=CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_cv, y_cv))

In [ ]:
import matplotlib.pyplot as plt

pd.DataFrame(history.history).plot(figsize=(8,5))
plt.grid(True)
plt.gca().set_ylim(0,1)
plt.show()

In [ ]:
#decreasing amount of neurons

import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense, Input
from keras.models import Sequential
from keras.losses import CategoricalCrossentropy

model = Sequential([
    Input(shape=X_train.shape[1:]),
    Dense(100, activation="relu"),
    Dense(50, activation="relu"),
    Dense(3, activation="linear"),
])

model.compile(optimizer="adam", loss=CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_cv, y_cv))

In [ ]:
# increasing amount of neurons

import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense, Input
from keras.models import Sequential
from keras.losses import CategoricalCrossentropy

model = Sequential([
    Input(shape=X_train.shape[1:]),
    Dense(600, activation="relu"),
    Dense(300, activation="relu"),
    Dense(3, activation="linear"),
])

model.compile(optimizer="adam", loss=CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_cv, y_cv))

In [ ]:
# adding regularization
from keras.regularizers import l2

model = Sequential([
    Input(shape=X_train.shape[1:]),
    Dense(300, activation="relu", kernel_regularizer=l2(0.001)),
    Dense(100, activation="relu", kernel_regularizer=l2(0.001)),
    Dense(3, activation="linear"),
])

model.compile(optimizer="adam", loss=CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_cv, y_cv))

In [ ]:
# try both l1 and l2 regularization 
from keras.regularizers import l1, l2
from keras.layers import Dropout

model_l2 = Sequential([
    Input(shape=X_train.shape[1:]),
    Dense(300, activation="relu", kernel_regularizer=l2(0.001)),
    Dense(100, activation="relu", kernel_regularizer=l2(0.001)),
    Dense(3, activation="linear"),
])

model_l1 = Sequential([
    Input(shape=X_train.shape[1:]),
    Dense(300, activation="relu", kernel_regularizer=l1(0.001)),
    Dense(100, activation="relu", kernel_regularizer=l1(0.001)),
    Dense(3, activation="linear"),
])

model_l1.compile(optimizer="adam", loss=CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
model_l2.compile(optimizer="adam", loss=CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history_l1 = model_l1.fit(X_train, y_train, epochs=50, validation_data=(X_cv, y_cv))
history_l2 = model_l2.fit(X_train, y_train, epochs=50, validation_data=(X_cv, y_cv))

In [ ]:
#keep l1

model = Sequential([
    Input(shape=X_train.shape[1:]),
    Dense(300, activation="relu", kernel_initializer="he_normal", kernel_regularizer=l1(0.001)),
    Dense(100, activation="relu", kernel_initializer="he_normal", kernel_regularizer=l1(0.001)),
    Dense(3, activation="linear"),
])

model.compile(optimizer="adam", loss=CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=50, validation_data=(X_cv, y_cv))

In [ ]:
#add more layers, and use functools.partial() function
from functools import partial

RegularizedDense = partial(Dense,
                          activation="relu",
                          kernel_initializer="he_normal",
                          kernel_regularizer=l2(0.01))

model = Sequential([
    Input(shape=X_train.shape[1:]),
    RegularizedDense(300),
    RegularizedDense(200),
    RegularizedDense(100),
    RegularizedDense(3, activation="linear"),
])

model.compile(optimizer="adam", loss=CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_cv, y_cv))

In [ ]:
#add more layers
from functools import partial

RegularizedDense = partial(Dense,
                          activation="relu",
                          kernel_initializer="he_normal",
                          kernel_regularizer=l2(0.01))

model = Sequential([
    Input(shape=X_train.shape[1:]),
    RegularizedDense(300),
    RegularizedDense(200),
    RegularizedDense(100),
    RegularizedDense(50),
    RegularizedDense(3, activation="linear"),
])

model.compile(optimizer="adam", loss=CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_cv, y_cv))

In [ ]:
#add much more epochs
from functools import partial

RegularizedDense = partial(Dense,
                          activation="relu",
                          kernel_initializer="he_normal",
                          kernel_regularizer=l2(0.01))

model = Sequential([
    Input(shape=X_train.shape[1:]),
    RegularizedDense(300),
    RegularizedDense(200),
    RegularizedDense(100),
    RegularizedDense(50),
    RegularizedDense(3, activation="linear"),
])

model.compile(optimizer="adam", loss=CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=500, validation_data=(X_cv, y_cv))

In [ ]:
#add much more epochs
from functools import partial

RegularizedDense = partial(Dense,
                          activation="relu",
                          kernel_initializer="he_normal",
                          kernel_regularizer=l2(0.01))

model = Sequential([
    Input(shape=X_train.shape[1:]),
    RegularizedDense(300),
    RegularizedDense(200),
    RegularizedDense(100),
    RegularizedDense(50),
    Dropout(0.5),
    RegularizedDense(3, activation="linear"),
])

model.compile(optimizer="adam", loss=CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_cv, y_cv))

In [ ]:
model = Sequential()
# Add other layers (e.g., input, hidden layers) as needed
model.add(Input(shape=X_train.shape[1:])),
model.add(Dense(64, activation='relu'))  # Example input layer
model.add(Dense(64, activation='relu'))  # Example hidden layer
model.add(Dense(3, activation='softmax'))  # Output layer

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=70, batch_size=32, validation_data=(X_cv, y_cv))

In [ ]:
#add much more epochs
from functools import partial
from keras.regularizers import l2
from keras.losses import CategoricalCrossentropy
from keras.layers import Dropout

RegularizedDense = partial(Dense,
                          activation="relu",
                          kernel_initializer="he_normal",
                          kernel_regularizer=l2(0.01))

model = Sequential([
    Input(shape=X_train.shape[1:]),
    RegularizedDense(300),
    RegularizedDense(200),
    RegularizedDense(100),
    RegularizedDense(50),
    Dropout(0.5),
    RegularizedDense(3, activation="linear"),
])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_cv, y_cv))

In [ ]:
import numpy as np

p_preferred = model.predict(X_train)
sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f"two example output vectors:\n {sm_preferred[:2]}")
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

In [ ]:
#add much more epochs
from functools import partial
from keras.regularizers import l2
from keras.losses import SparseCategoricalCrossentropy
from keras.layers import Dropout
from tensorflow.keras.callbacks import EarlyStopping

RegularizedDense = partial(Dense,
                          activation="relu",
                          kernel_initializer="he_normal",
                          kernel_regularizer=l2(0.01))

model = Sequential([
    Input(shape=X_train.shape[1:]),
    RegularizedDense(300),
    RegularizedDense(200),
    RegularizedDense(100),
    RegularizedDense(50),
    Dropout(0.5),
    RegularizedDense(3, activation="linear"),
])

model.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_val, y_val), callbacks=[early_stopping_cb])

In [22]:
#add much more epochs
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.initializers import HeNormal
from functools import partial
from keras.regularizers import l2
from keras.layers import Dropout, Dense, Input
from keras.models import Sequential
from keras.losses import SparseCategoricalCrossentropy

early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)


RegularizedDense = partial(Dense,
                          activation="relu",
                          kernel_initializer=HeNormal(),
                          kernel_regularizer=l2(0.01))

model = Sequential([
    Input(shape=X_train.shape[1:]),
    RegularizedDense(300),
    RegularizedDense(200),
    RegularizedDense(100),
    RegularizedDense(50),
    Dropout(0.5),
    RegularizedDense(3, activation="linear"),
])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_val, y_val), callbacks=[early_stopping])

Epoch 1/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5277 - loss: 12.6943 - val_accuracy: 0.5421 - val_loss: 9.4774
Epoch 2/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5535 - loss: 8.7402 - val_accuracy: 0.5316 - val_loss: 6.9282
Epoch 3/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5478 - loss: 6.4951 - val_accuracy: 0.5421 - val_loss: 5.4020
Epoch 4/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5763 - loss: 5.0966 - val_accuracy: 0.5474 - val_loss: 4.3914
Epoch 5/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5749 - loss: 4.1872 - val_accuracy: 0.5211 - val_loss: 3.7009
Epoch 6/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5612 - loss: 3.5297 - val_accuracy: 0.5316 - val_loss: 3.1646
Epoch 7/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5721 - loss: 3.0381 - val_accuracy: 0.5316 - val_loss: 2.7669
Epoch 8/50
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5645 - loss: 2.6664 - val_accuracy: 0.5158 - val_loss